<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="display" uri="http://displaytag.sf.net"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>Hibernate Semina</title>

	<!-- CDN URL for jQuery UI css -->
	<link type="text/css" rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/themes/base/jquery-ui.css" media="all" />
	<!-- bootstrap css-->
	<link type="text/css" rel="stylesheet" href="/resources/bootstrap/css/bootstrap.css" media="all" />
	<!-- CSS -->
	<link type="text/css" rel="stylesheet" href="/resources/css/myapp.css" media="all" />

	<!-- CDN URL for jQuery & jQuery UI -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/i18n/jquery-ui-i18n.min.js"></script>
	<!-- jQuery Plugin -->
	<script type="text/javascript" src="/resources/js/jquery-plugins/jquery.form.js"></script>
	<script type="text/javascript" src="/resources/js/jquery-plugins/jquery.validate.js"></script>
	<script type="text/javascript" src="/resources/js/jquery-plugins/jquery.validate.ext.js"></script>
	<!-- bootstrap javascript -->
	<link type="text/css" rel="stylesheet" href="/resources/bootstrap/js/bootstrap.js" media="all" />
	<!-- Javascript -->
	<script type="text/javascript" src="/resources/js/myapp.js"></script>
</head>

<body>